#pragma once

#define TAG_EDITOR_SPAWNER 1
#define TAG_EDITOR_BG 2
#define TAG_EDITOR_BG_SCORE 3
#define TAG_EDITOR_PLAYER_SPAWNPOINT 4
#define TAG_EDITOR_SPAWNCONTROLLER 4

#define TAG_GAME_LAYER_BACKGROUND 10
#define TAG_GAME_LAYER_SCENERY 11
#define TAG_GAME_LAYER_PLAYER 12
#define TAG_GAME_LAYER_UI 13

#define TAG_GAME_PLAYERPAWN 100

#define TAG_GAME_COMNODE_AURADMG_SPRITE 1000
#define TAG_GAME_COMNODE_AURADMG_SHAPE 1001